spring.application.name=backend

# Datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.postgresql.driver-class-name=org.postgresql.Driver
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://[ServerIPAddress]:[Port];databaseName=[DatabaseName];encrypt=true;trustServerCertificate=true

# OpenAi
openai.api.url=https://api.openai.com/v1/chat/completions
openai.embedding.url=https://api.openai.com/v1/embeddings
openai.api.key=
spring.ai.openai.api-key=

# ViAn
vian.api.url=http://171.224.244.159:8106/textToSpeechApi/tts
vian.api.key=

# Gemini
gemini.api.url=https://api.gemini.com/v1/completions
gemini.api.key=

# Redis
spring.redis.host=localhost
spring.redis.port=6377
spring.redis.password=hoabinh12
spring.redis.timeout=2000
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=5
spring.redis.jedis.pool.min-idle=1

# Elasticsearch
elasticsearch.username=elastic
elasticsearch.password=changeme
elasticsearch.host=localhost
elasticsearch.port=9201

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

# SSL
server.port=8888
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=hoabinh12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mycert

# Proxy
proxy.host=10.207.156.52
proxy.port=3128