
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    # An important note about accessing Kafka from clients on other machines: 
    # -----------------------------------------------------------------------
    #
    # The config used here exposes port 9092 for _external_ connections to the broker
    # i.e. those from _outside_ the docker network. This could be from the host machine
    # running docker, or maybe further afield if you've got a more complicated setup. 
    # If the latter is true, you will need to change the value 'localhost' in 
    # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those 
    # remote clients
    #
    # For connections _internal_ to the docker network, such as from other services
    # and components, use kafka:29092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    #
version: '3.8'
services:
  #Initialize zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000                                       # Heartbeat(ms)
      ZOOKEEPER_INIT_LIMIT: 5                                         # Specify the maximum number of tick intervals a follower can take to initialize with the leader
      ZOOKEEPER_SYNC_LIMIT: 2                                         # Specify the maximum number of tick intervals that can pass between sending a request and receiving an acknowledgment.
    ports:
      - "2181:2181"
    container_name: zookeeper_1
    healthcheck:
      test: nc -z zookeeper 2181 || exit -1                                                         # Check if port 2182 is open
      start_period: 15s                                                                             # Defines the period to wait before starting to perform health checks.
      interval: 5s
      timeout: 10s                                                                                  # Specifies the maximum time allowed for a single health check to complete, longer than this will be considdered as fail.
      retries: 10                                                                                   # Determines the number of consecutive failures needed to mark the service as unhealthy

  broker_01:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy                                                                  # Initialize broker_01 after zookeeper is confirmed healthy
    container_name: broker_01
    environment:
      KAFKA_BROKER_ID: 1                                                                            # Assigns a unique ID to each Kafka broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181                                                       # This tells the Kafka broker how to connect to Zookeeper, which is used for managing cluster metadata and leader election.
      KAFKA_LISTENERS: PLAINTEXT_HOST://broker_01:9092,PLAINTEXT://broker_01:29092                  # Specifies the protocols and ports the broker will use to listen for connections from clients and other brokers
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker_01:29092       # These are the addresses that clients will use to connect to the broker.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT            # Defines the security protocol to use for each listener name
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT                                                   # Specifies which listener should be used for communication between brokers in the cluster
      KAFKA_JMX_PORT: 9090                                                                          # This port is used for JMX monitoring and management of the Kafka broker
      KAFKA_LOG_DIRS: /var/lib/kafka/data                                                           # Kafka stores its data in these directories. Each log directory should be on a separate disk for better performance
      KAFKA_NUM_PARTITIONS: 2                                                                       #  This value determines how many partitions are created by default when a new topic is created
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                                     # The offsets topic stores consumer offsets. This setting determines how many replicas of this topic are maintained across the cluster
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1                                                        # This is the minimum number of replicas that must acknowledge a write for it to be considered successful. This ensures durability and consistency of transactional state.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1                                             # This determines how many replicas of the transaction state log are maintained. A higher replication factor increases fault tolerance
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100                                                   # This delay helps to avoid too frequent rebalancing, which can be expensive in terms of performance
      CONFLUENT_METRICS_ENABLE: 'false'
    ports:
      - 9092:9092
    healthcheck:
      test: nc -z broker_01 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10  

  broker_02:
      image: confluentinc/cp-kafka:latest
      depends_on:
        zookeeper:
          condition: service_healthy
      container_name: broker_02
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT_HOST://broker_02:9094,PLAINTEXT://broker_02:29092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9094,PLAINTEXT://broker_02:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_JMX_PORT: 9090
        KAFKA_LOG_DIRS: /var/lib/kafka/data
        KAFKA_NUM_PARTITIONS: 2
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
        CONFLUENT_METRICS_ENABLE: 'false'
      ports:
        - 9094:9094
      healthcheck:
        test: nc -z broker_02 9094 || exit -1
        start_period: 15s
        interval: 5s
        timeout: 10s
        retries: 10


  kafka-ui:
    container_name: kafka-ui_1
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      broker_01:
        condition: service_healthy
      broker_02:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: vdt-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker_01:29092,broker_02:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9090
    healthcheck:
      test: nc -z kafka-ui 8080 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10